import { Counter, Histogram, Gauge, Registry } from 'prom-client';
export declare const register: Registry<"text/plain; version=0.0.4; charset=utf-8">;
export declare const httpRequestDuration: Histogram<"method" | "route" | "status">;
export declare const httpRequestsTotal: Counter<"method" | "route" | "status">;
export declare const telemetryReceivedTotal: Counter<"metric_type">;
export declare const alertsCreatedTotal: Counter<"alert_type" | "severity">;
export declare const alertsActiveCount: Gauge<"severity">;
export declare const emergencyCallsPending: Gauge<string>;
export declare const aiPredictionsTotal: Counter<"prediction_type" | "model_id">;
export declare const aiPredictionsFailedTotal: Counter<"model_id">;
export declare const notificationsSentTotal: Counter<"status" | "channel">;
export declare const notificationsFailedTotal: Counter<"channel">;
export declare const activeUsersCount: Gauge<string>;
export declare const telemetryProcessingLag: Gauge<string>;
export declare const dbQueryDuration: Histogram<"status" | "query">;
export declare const dbConnectionsActive: Gauge<string>;
export declare const rabbitmqMessagesPublished: Counter<"exchange" | "routing_key">;
export declare const rabbitmqMessagesConsumed: Counter<"status" | "queue">;
export declare function recordHttpRequest(method: string, route: string, status: number, duration: number): void;
export declare function getMetrics(): Promise<string>;
